#!/usr/bin/env python3
"""
Convert binary file to Verilog initialization for IRAM
Usage: python3 bin2mif.py input.bin output.v
"""

import sys

def bin2verilog(bin_file, out_file):
    """Convert binary file to Verilog $readmemh format"""

    with open(bin_file, 'rb') as f:
        data = f.read()

    # Pad to word-aligned
    while len(data) % 4 != 0:
        data += b'\x00'

    words = []
    for i in range(0, len(data), 4):
        word = int.from_bytes(data[i:i+4], byteorder='little')
        words.append(word)

    # Generate Verilog initialization (pure hex, no comments for $readmemh)
    with open(out_file, 'w') as f:
        for i, w in enumerate(words):
            f.write(f"{w:08x}\n")

    print(f"Generated {out_file} with {len(words)} words ({len(words)*4} bytes)")

    # Also create a C header with the data (only if output is .hex)
    header_file = out_file.replace('.hex', '.h')
    with open(header_file, 'w') as f:
        f.write("// Auto-generated by bin2mif.py\n")
        f.write("#ifndef __IRAM_INIT_H__\n")
        f.write("#define __IRAM_INIT_H__\n\n")
        f.write(f"#define IRAM_SIZE {len(words)}\n\n")
        f.write("static const unsigned int iram_init[] = {\n")
        for i in range(0, len(words), 8):
            line = ", ".join(f"0x{w:08x}" for w in words[i:i+8])
            f.write(f"    {line},\n")
        f.write("};\n\n")
        f.write("#endif // __IRAM_INIT_H__\n")

    print(f"Generated {header_file}")

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: bin2mif.py <input.bin> <output.v>")
        sys.exit(1)

    bin2verilog(sys.argv[1], sys.argv[2])
